module.exports = [
  {
    files: ["app.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        fetch: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        location: "readonly",
        history: "readonly",
        XMLHttpRequest: "readonly",
        Promise: "readonly",
        Capacitor: "readonly",
        CapacitorApp: "readonly",
        performance: "readonly",
        FormData: "readonly",
        Blob: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        ResizeObserver: "readonly",
        getComputedStyle: "readonly",
        matchMedia: "readonly",
        crypto: "readonly",
        btoa: "readonly",
        atob: "readonly",
        Image: "readonly",
        Audio: "readonly",
        WebSocket: "readonly",
        Worker: "readonly",
        indexedDB: "readonly",
        globalThis: "readonly",
        self: "readonly",
        top: "readonly",
        parent: "readonly",
        Node: "readonly",
        NodeFilter: "readonly",
        DOMParser: "readonly",
        Element: "readonly",
        HTMLElement: "readonly",
        Document: "readonly",
        Notification: "readonly",
        gtag: "readonly",
        dataLayer: "writable",
        firebase: "readonly",
        debugLog: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": ["warn", { args: "none", varsIgnorePattern: "^_" }],
      "no-redeclare": "error",
      "no-dupe-keys": "error",
      "no-dupe-args": "error",
      "no-dupe-class-members": "error",
      "no-unreachable": "error",
      "no-const-assign": "error",
      "no-cond-assign": "error",
      "no-unsafe-negation": "error",
      "no-func-assign": "error",
      "no-import-assign": "error",
      "no-obj-calls": "error",
      "no-self-assign": "error",
      "no-self-compare": "error",
      "no-dupe-else-if": "error",
      "no-duplicate-case": "error",
      "no-fallthrough": "error",
      "no-irregular-whitespace": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
      "no-compare-neg-zero": "error",
      "no-empty": ["warn", { allowEmptyCatch: true }],
      "no-ex-assign": "error",
      "no-sparse-arrays": "error",
      "no-unsafe-finally": "error",
      "constructor-super": "error",
      "no-this-before-super": "error",
      "no-class-assign": "error",
      "no-async-promise-executor": "warn",
      "no-misleading-character-class": "error",
      "no-unmodified-loop-condition": "warn",
      "no-constant-condition": ["warn", { checkLoops: false }],
    },
  },
];
